<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Modelo.edmx" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="Modelo.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>Modelo.Designer.cs</LastGenOutput>
    </EntityDeploy>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.4.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Modelo.Context.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.Context.tt</DependentUpon>
    </Compile>
    <Compile Update="Modelo.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.tt</DependentUpon>
    </Compile>
    <Compile Update="Modelo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.edmx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Modelo.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Modelo.Context.cs</LastGenOutput>
    </None>
    <None Update="Modelo.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Modelo.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entidades\Extensiones\" />
  </ItemGroup>

</Project>
