//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurneroCola
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Servicio { get; set; }
        public System.DateTime FechaHoraEmision { get; set; }
        public string Estado { get; set; }
        public Nullable<int> BoxAsignado { get; set; }
        public Nullable<System.DateTime> FechaHoraLlamado { get; set; }
    }
}
